on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: "Build on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (ubuntu-latest)
        run: |
          sudo apt-get install qemu-system-x86 ovmf

      - name: Initialize Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Initialize Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Execute build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --no-daemon
